//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.MSBuildTasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.MSBuildTasks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT returned error {0}.
        /// </summary>
        internal static string Git_Error {
            get {
                return ResourceManager.GetString("Git_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT ISO8601 format unrecognized.
        /// </summary>
        internal static string Git_InvalidIso8601 {
            get {
                return ResourceManager.GetString("Git_InvalidIso8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT &apos;log&apos; returned no commits for path &apos;{0}&apos;.
        /// </summary>
        internal static string Git_LogNoCommits {
            get {
                return ResourceManager.GetString("Git_LogNoCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT &apos;log&apos; returned unexpected output for path &apos;{0}&apos;.
        /// </summary>
        internal static string Git_LogUnexpectedOutput {
            get {
                return ResourceManager.GetString("Git_LogUnexpectedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT tools not available.
        /// </summary>
        internal static string Git_ToolsNotAvailable {
            get {
                return ResourceManager.GetString("Git_ToolsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT returned unexpected output.
        /// </summary>
        internal static string Git_UnexpectedOutput {
            get {
                return ResourceManager.GetString("Git_UnexpectedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End operation type was different than Begin.
        /// </summary>
        internal static string Infra_IO_AsyncResult_EndInvalidOperation {
            get {
                return ResourceManager.GetString("Infra_IO_AsyncResult_EndInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End was called multiple times for this operation.
        /// </summary>
        internal static string Infra_IO_AsyncResult_EndMultipleCalls {
            get {
                return ResourceManager.GetString("Infra_IO_AsyncResult_EndMultipleCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End was called on a different object than Begin.
        /// </summary>
        internal static string Infra_IO_AsyncResult_EndWithInvalidObject {
            get {
                return ResourceManager.GetString("Infra_IO_AsyncResult_EndWithInvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result passed represents an operation not supported by this framework.
        /// </summary>
        internal static string Infra_IO_AsyncResult_UnsupportedResult {
            get {
                return ResourceManager.GetString("Infra_IO_AsyncResult_UnsupportedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation: Must first locate the executable.
        /// </summary>
        internal static string Infra_Process_ExeNotFound {
            get {
                return ResourceManager.GetString("Infra_Process_ExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process not exited.
        /// </summary>
        internal static string Infra_Process_NotComplete {
            get {
                return ResourceManager.GetString("Infra_Process_NotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was already executed. Instantiate a new object.
        /// </summary>
        internal static string Infra_Process_RunProcess_ExecuteTwice {
            get {
                return ResourceManager.GetString("Infra_Process_RunProcess_ExecuteTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown source provider.
        /// </summary>
        internal static string Infra_Source_UnknownProvider {
            get {
                return ResourceManager.GetString("Infra_Source_UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial count must be zero or greater.
        /// </summary>
        internal static string Infra_Tasks_InitialCountZero {
            get {
                return ResourceManager.GetString("Infra_Tasks_InitialCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tool.
        /// </summary>
        internal static string Infra_Tools_InvalidTool {
            get {
                return ResourceManager.GetString("Infra_Tools_InvalidTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signtool.exe could not be found.
        /// </summary>
        internal static string SignTool_ToolsNotAvailable {
            get {
                return ResourceManager.GetString("SignTool_ToolsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate file not defined.
        /// </summary>
        internal static string X509_Cert_ArgumentNull {
            get {
                return ResourceManager.GetString("X509_Cert_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate path property CertPath is not defined..
        /// </summary>
        internal static string X509_Cert_CertPathNotDefined {
            get {
                return ResourceManager.GetString("X509_Cert_CertPathNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate file &apos;{0}&apos; couldn&apos;t be opened: {1}.
        /// </summary>
        internal static string X509_Cert_FileInvalid {
            get {
                return ResourceManager.GetString("X509_Cert_FileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate path property CertPath &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string X509_Cert_FileNotFound {
            get {
                return ResourceManager.GetString("X509_Cert_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate file &apos;{0}&apos; to be used.
        /// </summary>
        internal static string X509_Cert_Found {
            get {
                return ResourceManager.GetString("X509_Cert_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Signing {0} with {1}: {2}..
        /// </summary>
        internal static string X509_Cert_SignError {
            get {
                return ResourceManager.GetString("X509_Cert_SignError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing &apos;{0}&apos; with Certificate file &apos;{1}&apos;..
        /// </summary>
        internal static string X509_Cert_SignMessage {
            get {
                return ResourceManager.GetString("X509_Cert_SignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact to sign InputAssembly is not defined..
        /// </summary>
        internal static string X509_Input_AssemblyNotDefined {
            get {
                return ResourceManager.GetString("X509_Input_AssemblyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string X509_Input_FileNotFound {
            get {
                return ResourceManager.GetString("X509_Input_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignTool failed with exit code {0}..
        /// </summary>
        internal static string X509_SignTool_Failure {
            get {
                return ResourceManager.GetString("X509_SignTool_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignTool found at &apos;{0}&apos;..
        /// </summary>
        internal static string X509_SignTool_Found {
            get {
                return ResourceManager.GetString("X509_SignTool_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignTool completed with exit code 0..
        /// </summary>
        internal static string X509_SignTool_Success {
            get {
                return ResourceManager.GetString("X509_SignTool_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Timestamp: {0}.
        /// </summary>
        internal static string X509_TimeStamp_Found {
            get {
                return ResourceManager.GetString("X509_TimeStamp_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timestamp URI is empty and won&apos;t be used..
        /// </summary>
        internal static string X509_TimeStamp_Ignored {
            get {
                return ResourceManager.GetString("X509_TimeStamp_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timestamp URI &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string X509_TimeStamp_Invalid {
            get {
                return ResourceManager.GetString("X509_TimeStamp_Invalid", resourceCulture);
            }
        }
    }
}
